[package]
name = "ruster-tui"
version = "0.1.1"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
ruster-core = { path = "../ruster-core" }
ruster-render = { path = "../ruster-render" }
ruster-syntax = { path = "../ruster-syntax" }
ruster-lua = { path = "../ruster-lua" }
ruster-lsp = { path = "../ruster-lsp" }
ruster-terminal = { path = "../ruster-terminal" }
ruster-git = { path = "../ruster-git" }
ruster-project = { path = "../ruster-project" }
ruster-dap = { path = "../ruster-dap" }
ruster-notify = { path = "../ruster-notify" }
serde_json = "1"
ratatui = "0.28"
crossterm = "0.28"
tokio = { version = "1", features = ["rt", "time", "sync", "macros"] }
dirs = "5"
ruster-picker = { path = "../ruster-picker" }
ignore = "0.4"
