use crossterm::event::{KeyEvent, KeyCode, KeyModifiers};

pub fn map_raylib_key(key: raylib::consts::KeyboardKey) -> Option<KeyEvent> {
    use raylib::consts::KeyboardKey::*;
    let code = match key {
        KEY_A => KeyCode::Char('a'),
        KEY_B => KeyCode::Char('b'),
        KEY_C => KeyCode::Char('c'),
        KEY_D => KeyCode::Char('d'),
        KEY_E => KeyCode::Char('e'),
        KEY_F => KeyCode::Char('f'),
        KEY_G => KeyCode::Char('g'),
        KEY_H => KeyCode::Char('h'),
        KEY_I => KeyCode::Char('i'),
        KEY_J => KeyCode::Char('j'),
        KEY_K => KeyCode::Char('k'),
        KEY_L => KeyCode::Char('l'),
        KEY_M => KeyCode::Char('m'),
        KEY_N => KeyCode::Char('n'),
        KEY_O => KeyCode::Char('o'),
        KEY_P => KeyCode::Char('p'),
        KEY_Q => KeyCode::Char('q'),
        KEY_R => KeyCode::Char('r'),
        KEY_S => KeyCode::Char('s'),
        KEY_T => KeyCode::Char('t'),
        KEY_U => KeyCode::Char('u'),
        KEY_V => KeyCode::Char('v'),
        KEY_W => KeyCode::Char('w'),
        KEY_X => KeyCode::Char('x'),
        KEY_Y => KeyCode::Char('y'),
        KEY_Z => KeyCode::Char('z'),
        KEY_ZERO => KeyCode::Char('0'),
        KEY_ONE => KeyCode::Char('1'),
        KEY_TWO => KeyCode::Char('2'),
        KEY_THREE => KeyCode::Char('3'),
        KEY_FOUR => KeyCode::Char('4'),
        KEY_FIVE => KeyCode::Char('5'),
        KEY_SIX => KeyCode::Char('6'),
        KEY_SEVEN => KeyCode::Char('7'),
        KEY_EIGHT => KeyCode::Char('8'),
        KEY_NINE => KeyCode::Char('9'),
        KEY_SPACE => KeyCode::Char(' '),
        KEY_ENTER => KeyCode::Enter,
        KEY_BACKSPACE => KeyCode::Backspace,
        KEY_TAB => KeyCode::Tab,
        KEY_ESCAPE => KeyCode::Esc,
        KEY_LEFT => KeyCode::Left,
        KEY_RIGHT => KeyCode::Right,
        KEY_UP => KeyCode::Up,
        KEY_DOWN => KeyCode::Down,
        KEY_HOME => KeyCode::Home,
        KEY_END => KeyCode::End,
        KEY_PAGE_UP => KeyCode::PageUp,
        KEY_PAGE_DOWN => KeyCode::PageDown,
        KEY_DELETE => KeyCode::Delete,
        KEY_COMMA => KeyCode::Char(','),
        KEY_PERIOD => KeyCode::Char('.'),
        KEY_SLASH => KeyCode::Char('/'),
        KEY_SEMICOLON => KeyCode::Char(';'),
        KEY_APOSTROPHE => KeyCode::Char('\''),
        KEY_LEFT_BRACKET => KeyCode::Char('['),
        KEY_RIGHT_BRACKET => KeyCode::Char(']'),
        KEY_GRAVE => KeyCode::Char('`'),
        KEY_MINUS => KeyCode::Char('-'),
        KEY_EQUAL => KeyCode::Char('='),
        KEY_BACKSLASH => KeyCode::Char('\\'),
        KEY_BACK => KeyCode::Esc,
        _ => return None,
    };
    Some(KeyEvent::new(code, KeyModifiers::empty()))
}
