//! Loading tree-sitter grammars from disk at runtime (Phase 6 Task 16).
//!
//! The compiled-in grammars in [`language_for_ext`](crate::language_for_ext)
//! stay exactly as they are and remain the fallback. This module is a
//! resolution layer *on top*: if the user has built a grammar into
//! `~/.config/ruster/grammars/`, it wins.
//!
//! # Why the ABI check is the whole point
//!
//! `dlopen`ing a library and calling into it is `unsafe`, and a grammar
//! generated by a different tree-sitter CLI than the 0.25 this workspace links
//! does not fail politely — `ts_parser_set_language` returns false, but any
//! query compiled against it walks a struct whose layout has changed and
//! **segfaults the editor**.
//!
//! What makes the check possible is that `ts_language_abi_version` reads the
//! *first field* of `TSLanguage`, and that field has been first in every ABI
//! tree-sitter has shipped. Reading it is therefore the one thing that is safe
//! to do with a language of unknown vintage, and nothing else here touches the
//! language until it has passed.
//!
//! A refused grammar is a missing highlight. A wrong one is a crash. When in
//! doubt this module refuses.
//!
//! The tests here cover the ABI predicate and the symbol lookup but never load a
//! real grammar — that needs a C compiler and a tree-sitter CLI which CI does
//! not have. `examples/load_runtime_grammar.rs` does, and documents how; it was
//! run against real libraries at ABI 12, 13, 15 and 99 to confirm the boundary
//! behaves as specified and that a refusal degrades rather than crashing.

use std::path::{Path, PathBuf};

use tree_sitter::Language;

/// Why a grammar could not be loaded. None of these are fatal — every one falls
/// back to the compiled-in grammar.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum GrammarError {
    /// No library for this language in the directory. The normal case, and the
    /// only one that is not worth reporting.
    NotFound,
    /// The file exists but `dlopen` refused it.
    Load(String),
    /// Opened, but has no `tree_sitter_<lang>` entry point — almost always the
    /// wrong file, or a language name that does not match the file name.
    MissingSymbol(String),
    /// Built against an incompatible tree-sitter. Refused deliberately.
    AbiMismatch { found: usize, min: usize, max: usize },
}

impl std::fmt::Display for GrammarError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            GrammarError::NotFound => write!(f, "no grammar library found"),
            GrammarError::Load(e) => write!(f, "could not load: {e}"),
            GrammarError::MissingSymbol(s) => write!(f, "no `{s}` entry point"),
            GrammarError::AbiMismatch { found, min, max } => write!(
                f,
                "grammar is ABI {found}, but this build supports {min}–{max} \
                 — rebuild it with a matching tree-sitter CLI"
            ),
        }
    }
}

/// Whether a grammar's ABI version is one this build can safely use.
///
/// Pure, so the decision itself is testable without a library to load.
pub fn abi_supported(version: usize) -> bool {
    (tree_sitter::MIN_COMPATIBLE_LANGUAGE_VERSION..=tree_sitter::LANGUAGE_VERSION)
        .contains(&version)
}

/// Where user-built grammars live: `~/.config/ruster/grammars/`, honouring
/// `XDG_CONFIG_HOME` — the same discovery as themes and queries.
pub fn user_grammar_dir() -> Option<PathBuf> {
    if let Some(xdg) = std::env::var_os("XDG_CONFIG_HOME") {
        if !xdg.is_empty() {
            return Some(PathBuf::from(xdg).join("ruster").join("grammars"));
        }
    }
    dirs::home_dir().map(|h| h.join(".config").join("ruster").join("grammars"))
}

/// Candidate file names for `lang`, most conventional first.
///
/// Both the `lib`-prefixed name that a normal build produces and the bare one
/// that `tree-sitter build` emits, since users arrive with either.
pub fn library_names(lang: &str) -> Vec<String> {
    let ext = if cfg!(target_os = "windows") {
        "dll"
    } else if cfg!(target_os = "macos") {
        "dylib"
    } else {
        "so"
    };
    vec![format!("libtree-sitter-{lang}.{ext}"), format!("tree-sitter-{lang}.{ext}"), format!("{lang}.{ext}")]
}

/// The first candidate library for `lang` that exists in `dir`.
pub fn find_library(dir: &Path, lang: &str) -> Option<PathBuf> {
    library_names(lang).into_iter().map(|n| dir.join(n)).find(|p| p.is_file())
}

/// Load the grammar for `lang` from `dir`, refusing anything whose ABI this
/// build cannot use.
///
/// The returned [`Language`] borrows from the loaded library, so the library is
/// **deliberately leaked**: it must stay mapped for as long as any tree parsed
/// with it survives, and tracking that lifetime across every buffer would buy
/// nothing — a grammar is loaded once and used until exit. Unloading it while a
/// tree still pointed into it would be a use-after-free.
pub fn load_grammar(dir: &Path, lang: &str) -> Result<Language, GrammarError> {
    let path = find_library(dir, lang).ok_or(GrammarError::NotFound)?;

    // SAFETY: loading arbitrary user-supplied code is inherently unsafe and is
    // the point of the feature — the user placed this file there deliberately,
    // as they would a plugin. The library is never unloaded (see below), so no
    // symbol can dangle.
    let lib = unsafe { libloading::Library::new(&path) }
        .map_err(|e| GrammarError::Load(e.to_string()))?;
    language_from_library(lib, lang)
}

/// The half of [`load_grammar`] that finds the entry point and gates on ABI,
/// separated so it can be tested against a library that really is loaded —
/// producing a fixture grammar would otherwise need a compiler in the test.
fn language_from_library(lib: libloading::Library, lang: &str) -> Result<Language, GrammarError> {
    let symbol = format!("tree_sitter_{}", lang.replace('-', "_"));
    // SAFETY: the signature is fixed by tree-sitter's codegen — every generated
    // grammar exports exactly `const TSLanguage *tree_sitter_NAME(void)`. If the
    // symbol is absent this errors instead of calling anything.
    let language = unsafe {
        let entry: libloading::Symbol<unsafe extern "C" fn() -> *const std::ffi::c_void> =
            lib.get(symbol.as_bytes()).map_err(|_| GrammarError::MissingSymbol(symbol.clone()))?;
        // Calling the entry point only returns a pointer to a static descriptor;
        // it does not interpret it. The ABI check below happens before anything
        // else reads through that pointer.
        Language::from_raw(entry() as *const _)
    };

    let found = language.abi_version();
    if !abi_supported(found) {
        // Drop the library: nothing holds a reference to it, and refusing the
        // grammar means we will never touch this `Language` again.
        drop(lib);
        return Err(GrammarError::AbiMismatch {
            found,
            min: tree_sitter::MIN_COMPATIBLE_LANGUAGE_VERSION,
            max: tree_sitter::LANGUAGE_VERSION,
        });
    }

    // Past the gate: keep the library mapped forever.
    std::mem::forget(lib);
    Ok(language)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicUsize, Ordering};

    static FIXTURE: AtomicUsize = AtomicUsize::new(0);

    fn fixture(files: &[&str]) -> PathBuf {
        let id = FIXTURE.fetch_add(1, Ordering::Relaxed);
        let root = std::env::temp_dir().join(format!("ruster_grammars_{id}"));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&root).unwrap();
        for f in files {
            std::fs::write(root.join(f), "not a real library").unwrap();
        }
        root
    }

    /// The gate that stops a mismatched grammar from segfaulting the editor.
    #[test]
    fn only_abi_versions_this_build_supports_are_accepted() {
        let (min, max) =
            (tree_sitter::MIN_COMPATIBLE_LANGUAGE_VERSION, tree_sitter::LANGUAGE_VERSION);
        assert!(abi_supported(min), "the floor is usable");
        assert!(abi_supported(max), "so is the current version");
        assert!(!abi_supported(min - 1), "one below the floor is refused");
        assert!(!abi_supported(max + 1), "and so is anything newer than we know");
        assert!(!abi_supported(0), "a zeroed or garbage version is refused");
    }

    /// Every compiled-in grammar must itself pass the gate — otherwise the
    /// check is calibrated wrongly and would reject valid user grammars too.
    #[test]
    fn the_builtin_grammars_satisfy_their_own_abi_check() {
        for ext in ["rs", "py", "js", "ts", "c", "json", "toml", "yaml", "lua", "scm", "just"] {
            let lang = crate::language_for_ext(ext).expect("built in");
            assert!(
                abi_supported(lang.abi_version()),
                "{ext} is ABI {} which this build would refuse",
                lang.abi_version()
            );
        }
    }

    /// The overwhelmingly common case: nothing installed, so nothing to report.
    #[test]
    fn an_absent_library_is_not_found_rather_than_an_error() {
        let dir = fixture(&[]);
        assert_eq!(load_grammar(&dir, "rust"), Err(GrammarError::NotFound));
        assert_eq!(find_library(&dir, "rust"), None);
    }

    #[test]
    fn library_names_cover_the_conventions_users_arrive_with() {
        let names = library_names("rust");
        assert!(names[0].starts_with("libtree-sitter-rust."), "{names:?}");
        assert!(names.iter().any(|n| n.starts_with("tree-sitter-rust.")));
        let ext = names[0].rsplit('.').next().unwrap();
        #[cfg(target_os = "macos")]
        assert_eq!(ext, "dylib");
        #[cfg(target_os = "linux")]
        assert_eq!(ext, "so");
        #[cfg(target_os = "windows")]
        assert_eq!(ext, "dll");
    }

    #[test]
    fn find_library_prefers_the_lib_prefixed_name() {
        let names = library_names("rust");
        let dir = fixture(&[&names[0], &names[1]]);
        assert_eq!(find_library(&dir, "rust"), Some(dir.join(&names[0])));
    }

    /// A file that is not a library at all must be reported, not skipped — the
    /// user plainly meant it to be used.
    #[test]
    fn a_file_that_is_not_a_library_reports_a_load_error() {
        let dir = fixture(&[&library_names("rust")[0]]);
        match load_grammar(&dir, "rust") {
            Err(GrammarError::Load(_)) => {}
            other => panic!("expected a load error, got {other:?}"),
        }
    }

    /// A library that really is loaded but has no grammar entry point.
    ///
    /// Uses the test binary itself, which is guaranteed to exist and to be
    /// `dlopen`-able on every platform CI runs — building a fixture grammar
    /// would need a C compiler and a tree-sitter CLI in the test.
    #[test]
    fn a_library_without_the_entry_point_is_refused() {
        let exe = std::env::current_exe().expect("the test binary");
        let Ok(lib) = (unsafe { libloading::Library::new(&exe) }) else {
            // Some platforms refuse to dlopen an executable; the load-error path
            // is covered separately, so there is nothing left to assert here.
            return;
        };
        match language_from_library(lib, "definitelynotalanguage") {
            Err(GrammarError::MissingSymbol(s)) => {
                assert_eq!(s, "tree_sitter_definitelynotalanguage");
            }
            other => panic!("expected a missing symbol, got {other:?}"),
        }
    }

    /// Hyphens in a language name become underscores in the C symbol.
    #[test]
    fn the_entry_point_name_is_c_identifier_safe() {
        let exe = std::env::current_exe().expect("the test binary");
        let Ok(lib) = (unsafe { libloading::Library::new(&exe) }) else { return };
        match language_from_library(lib, "some-lang") {
            Err(GrammarError::MissingSymbol(s)) => assert_eq!(s, "tree_sitter_some_lang"),
            other => panic!("expected a missing symbol, got {other:?}"),
        }
    }

    #[test]
    fn errors_say_what_to_do_about_them() {
        let e = GrammarError::AbiMismatch { found: 99, min: 13, max: 15 };
        let msg = e.to_string();
        assert!(msg.contains("99") && msg.contains("13") && msg.contains("15"), "{msg}");
        assert!(msg.contains("rebuild"), "tells the user the fix: {msg}");
    }

    #[test]
    fn the_grammar_dir_sits_beside_the_other_config_dirs() {
        let dir = user_grammar_dir().expect("a home directory");
        assert!(dir.ends_with("ruster/grammars"), "{}", dir.display());
    }
}
